# Generated by Django 2.0.6 on 2021-10-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprogra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lap',
            fields=[
                ('pk_lap', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rom', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Salary',
        ),
    ]
